#pragma once


#define CHAT_SERV_IP_ADDR_STR				"127.0.0.1"
#define CHAT_SERV_PORT						6000
#define CHAT_SERV_LIMIT_ACCEPTANCE			1000

#define CHAT_TLS_MEM_POOL_DEFAULT_UNIT_CNT			1000
#define CHAT_TLS_MEM_POOL_DEFAULT_UNIT_CAPACITY		1000

#define CHAT_SERV_SESSION_SEND_BUFF_SIZE	30000
#define CHAT_SERV_SESSION_RECV_BUFF_SIZE	30000

#define MAX_WORKER_THREAD_CNT				32

#define CHAT_SERV_LIMIT_ACCEPTANCE			1000

//#define ENCODE_TEST